blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root to: 'posts#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

blog/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :content, presence: true
  belongs_to :user
  has_many :comments
end

blog/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # p comment_params
    # @comment = Post.find(4).comments.create(comment_params)
    @comment = Comment.new
    @comment.content = params[:content]
    @comment.user_id = 1
    @comment.post_id = 4
    @comment.save
    redirect_to post_path(4)
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = @post.comments.find(10)
    @comment.destroy
    redirect_to post_path
  end

  private
  def comment_params
    params.permit(:content,:post_id)
  end

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order(updated_at: :desc)
    end

    def new
        @post = Post.new
    end


    def create
        @post = User.find(1).posts.create(post_params)
        #@post = Post.create(post_params)

        if @post.id
            redirect_to :posts
        else
          render :new
        end
        #@post = Post.new
        #@post.title = params[:title]
        #@post.content = params[:content]
        #@post.save
        #redirect_to :posts
        #redirect_to action :index, controller :users
    end

    def edit
        @post = Post.find(params[:id])
    end


    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to :posts
        else
            render :edit
        end
    end

    def show
        @post = Post.find(4)
        @comment = Comment.new
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to :posts
    end

    private
    def post_params
        params.require(:post).permit(:title, :content)
    end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comment_helper.rb
module CommentHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href=<%= root_path%>>Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= new_post_path%>>New Post<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
  </nav>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

blog/app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger mt-3">
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@post, url: @post) do |f| %>
    <div class="mt-3">
      <h1>Create Post</h1>
    </div>
    <div class="form-group mt-3">
      <%= f.text_field(:title, placeholder: "enter title...", class: "form-control") %>
    </div>

    <div class="form-group">
      <%= f.text_area(:content, placeholder: "enter content...", class: "form-control", rows: "5") %>
    </div>

    <%= submit_tag btnt, class: "btn btn-#{btnc} btn-block" %>
<% end %>

blog/app/views/posts/edit.html.erb
<%= render partial: 'form', locals: {btnt: 'UPDATE', btnc: 'info'} %>

blog/app/views/posts/index.html.erb
<div class="mt-3">
  <h1>Posts</h1>
</div>
<% @posts.each do |post|%>
    <div class="card md-8 mb-3" style="background-color: lightblue">
      <div class="card-body">
        <h5 class="card-title">Title: <%= post.title  %></h5>
        <h5 class="card-title">User_Name: <%= post.user.name  %></h5>
        <h5 class="card-text"><%= post.content  %></h5>
        <a href="<%= edit_post_path(post) %>" class="btn btn-primary">Update</a>
        <%= link_to 'delete', post, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
        <a href="<%= post_path(post) %>" class="btn btn-warning">Show Post</a>
      </div>
    </div>
<% end %>

blog/app/views/posts/new.html.erb
<%= render partial: 'form', locals: {btnt: 'CREATE', btnc: 'success'} %>

blog/app/views/posts/show.html.erb
<div class="mt-3">
  <h1>
    Post Details
  </h1>
</div>
<div class="card md-8 mb-3" style="background-color: lightblue">
  <div class="card-body">
    <h5 class="card-title">Title: <%= @post.title  %></h5>
    <h5 class="card-title">User_Name: <%= @post.user.name  %></h5>
    <h5 class="card-text">Content<%= @post.content  %></h5>
    <h5 class="card-text">Last-Update: <%= @post.updated_at  %></h5>
  </div>
</div>

<% @post.comments.each do |comment| %>
    <% if comment.errors.any? %>
        <div class="alert alert-danger mt-3">
          <ul>
            <% comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>


<%= form_with(url: "/posts/#{@post.id}/comments", method: "post") do |f| %>
    <div class="mt-3">
      <h1>Write Comment</h1>
    </div>
    <div class="form-group mt-3">
      <%= f.text_area(:content, placeholder: "enter comment...", class: "form-control", rows: "3") %>
    </div>

    <%= submit_tag("Save",class: "btn btn-success btn-block")%>
<% end %>



<div class="mt-3">
  <h1>Comments</h1>
</div>
<% @post.comments.each do |comment|%>
    <div class="card md-8 mb-3" style="background-color: lightgray">
      <div class="card-body">
        <h5 class="card-text">Content: <%= comment.content  %></h5>
        <%= link_to 'delete', post_comment_path(@post), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
<% end %>